language: generic
sudo: false

addons:
  apt:
    packages:
    - texlive-latex-recommended
    - texlive-fonts-recommended
    - texlive-fonts-extra
    - texlive-latex-extra
    - texlive-science
    - latex-beamer
    - lmodern

script:
  - cd euroscipy-2017 && pdflatex -halt-on-error euroscipy-2017.tex && pdflatex euroscipy-2017.tex && cd -
  - cd lowranktensor && pdflatex -halt-on-error lowranktensor.tex && pdflatex lowranktensor.tex && cd -
  - for subdir in agenda overview architecture uncertainties library_development module_development tps; do cd developer/${subdir} && pdflatex -halt-on-error ${subdir}.tex && pdflatex ${subdir}.tex && cd -; done
  - cd uncecomp2017/Uncecomp2017-article-OT && pdflatex -halt-on-error uncecomp-2017-article-OpenTURNS.tex && bibtex uncecomp-2017-article-OpenTURNS && pdflatex uncecomp-2017-article-OpenTURNS.tex && pdflatex uncecomp-2017-article-OpenTURNS.tex && cd -
  - cd uncecomp2017/Uncecomp2017-slides-OT && pdflatex -halt-on-error uncecomp-2017-slides-OpenTURNS.tex && pdflatex uncecomp-2017-slides-OpenTURNS.tex && cd -
  - cd uncecomp2019/Uncecomp2019-article-OT && pdflatex -halt-on-error uncecomp-2019-article-OpenTURNS.tex && bibtex uncecomp-2019-article-OpenTURNS && pdflatex uncecomp-2019-article-OpenTURNS.tex && pdflatex uncecomp-2019-article-OpenTURNS.tex && cd -
  - cd uncecomp2019/Uncecomp2019-slides-OT && pdflatex -halt-on-error uncecomp-2019-slides-OpenTURNS.tex && pdflatex uncecomp-2019-slides-OpenTURNS.tex && cd -
  - cd chorus-2017-otfmi && pdflatex -halt-on-error chorus-2017-otfmi.tex && pdflatex chorus-2017-otfmi.tex && cd -

after_success:
  - test "$TRAVIS_PULL_REQUEST" = "false" -a "$TRAVIS_BRANCH" = "master" || exit 0
  - git clone https://${GH_TOKEN}@github.com/openturns/openturns.github.io.git
  - PROJECT_REPONAME=`echo "${TRAVIS_REPO_SLUG}" | cut -d "/" -f 2`
  - if test -n "${TRAVIS_TAG}"; then
        TRAVIS_BRANCH=${TRAVIS_TAG:1};
    fi
  - mkdir -p openturns.github.io/${PROJECT_REPONAME}/${TRAVIS_BRANCH}
  - cp -v ${TRAVIS_BUILD_DIR}/*/*.pdf ${TRAVIS_BUILD_DIR}/developer/*/*.pdf openturns.github.io/${PROJECT_REPONAME}/${TRAVIS_BRANCH}
  - cp -v ${TRAVIS_BUILD_DIR}/uncecomp2017/Uncecomp2017-article-OT/uncecomp-2017-article-OpenTURNS.pdf openturns.github.io/${PROJECT_REPONAME}/${TRAVIS_BRANCH}
  - cp -v ${TRAVIS_BUILD_DIR}/uncecomp2017/Uncecomp2017-slides-OT/uncecomp-2017-slides-OpenTURNS.pdf openturns.github.io/${PROJECT_REPONAME}/${TRAVIS_BRANCH}
  - cp -v ${TRAVIS_BUILD_DIR}/uncecomp2019/Uncecomp2019-article-OT/uncecomp-2019-article-OpenTURNS.pdf openturns.github.io/${PROJECT_REPONAME}/${TRAVIS_BRANCH}
  - cp -v ${TRAVIS_BUILD_DIR}/uncecomp2019/Uncecomp2019-slides-OT/uncecomp-2019-slides-OpenTURNS.pdf openturns.github.io/${PROJECT_REPONAME}/${TRAVIS_BRANCH}
  - cp -v ${TRAVIS_BUILD_DIR}/siamuq2016/siamuq-2016-OpenTURNS.pdf openturns.github.io/${PROJECT_REPONAME}/${TRAVIS_BRANCH}
  - cp -v ${TRAVIS_BUILD_DIR}/siamuq2018/siamuq-2018-OpenTURNS.pdf openturns.github.io/${PROJECT_REPONAME}/${TRAVIS_BRANCH}
  - cp -v ${TRAVIS_BUILD_DIR}/chorus-2017-otfmi/chorus-2017-otfmi.pdf openturns.github.io/${PROJECT_REPONAME}/${TRAVIS_BRANCH}
  - cd openturns.github.io
  - touch .nojekyll
  - git config user.email "support@travis-ci.com"
  - git config user.name "Travis CI"
  - git add -A .
  - git commit -a -m "Travis build ${PROJECT_REPONAME} ${TRAVIS_BUILD_NUMBER}"
  - git push --quiet origin master > /dev/null 2>&1

env:
  global:
    secure: "mC7PqtAvW2jWf7XhvLrg7LqftLalRgvjl/oXAx9Ni4Ng+DqqpXynbrGOIxMJRpjwWbP6BLI7TdTpz39Rw2/WEJmsh+IRtGyWIl4sWSkunIVIVM+bhEv1mH99MMrQDS19BqfyBPIcrWHt2UgfpgvnK4EXXNkHWFqzoovCZlweZY9baADKN8eS/SQnuVJpQinjvE6Ea4dub3e6y3KokNga1swmsd/S7b8L/8QYXrvbdyzdI+mGQPEdcAaIIt5+v+zGqTzvoLJ1l6hCmtB3xkhoV1l0zPRy9H8NE3Q39XihNF/YJOAT84uptAATVbLvKN9OwSNi27vuFUKW1QqozzB+e6lkekoewVy5odeJG/McGNq+JT0TvKORDsq2byoY7ohwRJXYiXwIyXyr1N7uF54hrGczLQYbBD4+xAkSZP7+t9ylpDwzCSQBo3ac66TN/QhQXjNKo1tYxgMzgtanEs3cLBNeYifmUVlPCBMgXm3sHP9zNA+zPjeoaUoJpl2LfrFYyVhFs53RR7R8nkRGg4+WZymslrWEv/1xQ+Z5zqIaJVkPsvRSueOOwgwub5bbIDR61wg8gjAoWfNmFx1KKlbBqV5XZdp+Ga561wknb0R41R1kDHjpZBzqF5yu56EOOGxinTeBiLQnq8XkEfKfPvHfQkQRGd9TKAbW3i5dPxYME9w="
